farcrycore/core

Application.cfc
Prior to checkin, bot ips were erroneously assigned to bot agents resulting in only bots with empty user agents being marked as bots.
Unable to test that fix corrects issue as cookies work for a user, but the code seems to work with the change.
=> (doc) Fix detection of bots via user agent

tags/webskin/buildLink.cfm
When using skin:building inside a cfoutput, extraneous white space is also produced. Not a major issue unless one has code like this:
<skin:buildLink alais="home>Home Page</skin:buildLink>.
This results in "Home Page ." due to the white space.
This commit removes the extra lines introduced
=> (doc) skin:buildlink whitespace

packages/lib/fapi.cfc, tags/webskin/buildLink.cfm
Update fapi.getLink so users can force a secure link to be returned
=> Get link return secure link

packages/formtools/creditcardexpiry.cfc, packages/formtools/creditcardnumber.cfc, packages/formtools/creditcardtype.cfc, packages/formtools/image.cfc
FarCry 6.3 does not have a "fc-jquery" registered JS library.  Normally this doesn't cause a problem since jquery is loaded on nearly every page anyway.  
However, in the FarCry Solr Pro plugin on versions of FC that do not have fc-jquery, we create it as a copy of the regular "jquery" library so that we can just require fc-query on all versions of farCry instead of having `<cfif>` calls everywhere.
So, what is happening on 6.3.2 sites that have the solr plugin installed are loading two copies of jQuery and things like the image formtool are broken because the tooltip and other jquery plugins are not attaching to the correct instance of jquery.
So, since FC 6.3.x does not have a fc-jquery library in core, then core should not be referencing it at all so I think this commit should be …
=> FarCry 6.3.x does not have a fc-jquery library

packages/lib/diff.cfc
Add boolean and list cases to fc object property diff
Function will now highlight differences where the ftType of the field is boolean or list. It determines that "yes", "1" and "true" values are not different as booleans. It also tries to show the list name as the highlighted value for list types.
=> (doc) extend object property comparision

packages/rules/container.cfc
Change debug lookup in URL to lookup in request.mode
This is more consistent as it can be set from the session and it is also checked against against the currently logged in user. A blind URL lookup overrides security settings and potential information from the cfdump can assist attackers
=> patch container debug lookup

packages/formtools/file.cfc, packages/formtools/image.cfc
This fixes errors when trying to copy/duplicate types that has properties with ftType file and/or image.
=> Fix for copying/duplicating files and images

webskin/dmNavigation/webtopBodyQuickBuilder.cfm
On Quick Builder wheh selecting the content type the webskin often doesn't display with the error: Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
=> error writing the webskin list

tags/formtools/objectadmin.cfm
The filter window would stay visible if a boolean existed because the value would end up being 0
=> Filter will now hide if booleans exist

packages/forms/configGeneral.cfc, packages/formtools/datetime.cfc, packages/types/dmProfile.cfc, webskin/dmProfile/editCLIENTUDUser.cfm, webskin/dmProfile/editGenericUser.cfm, webskin/dmProfile/editOwn.cfm
Added 24 hour time format option in dmProfile and extended the formtools to use session.dmProfile.timeFormat. session.dmProfile.timeFormat is cfparamed and defaults to 12h format.
=> FC-3071 support for 24 hour time format

tags/formtools/processformobjects.cfm
added bUseInstanceCache=false to ensure current data is returned
https://farcry.jira.com/projects/FC/issues/FC-3130?filter=allopenissues
=> FC-3130 - added bUseInstanceCache=false

packages/types/dmCron.cfc
ColdFusion 2018 has dropped support for the `requesttimeout` attribute of `<cfschedule>`.  It will throw an error if you use this attribute.
That said, if you have the setting enabled in the CF Admin to allow "extra" attributes when using an `attributeCollection`, then it will allow it.
So we can change the code to use an attribute collection which is passed to the cfschedule tag.  This will allow older versions of ACF to still use the `requesttimeout` attribute while keeping CF 2018 from throwing an error.
=> CF 2018 has dropped support for requesttimeout attribute of cfschedule

packages/formtools/file.cfc
usage:
```
<cfproperty name="processFile" 
type="string" default="" ftseq="10" 
ftType="file" ftDestination="/import/" ftAllowedFileExtensions="xls,xlsx" 
ftLocation="temp" 
ftLabel="Import File" 
/>
```
=> FC-3149 add ability for formtool to upload file to local temp cdn location

packages/cdn/local.cfc, packages/cdn/s3.cfc, packages/lib/cdn.cfc
`qExistingFiles = application.fc.lib.cdn.ioGetDirectoryListing(location='privatefiles',dir='/imports', listinfo='all')`
=> FC-3157 - added ability to return file attibutes in ioGetDirectoryListing()

packages/cdn/s3.cfc
QueryAddColumn requires a min of 3 params
=> Fix breaking error on ACF

packages/cdn/ftp.cfc, packages/cdn/local.cfc, packages/cdn/s3.cfc
add bDebug (default false) to location config to reduce amount of information logging in S3 CDN library
**usage:**
```
<cfset application.fc.lib.cdn.setLocation(
name = "images",
cdn = "s3",
accessKeyId = accessKeyId,
awsSecretKey = awsSecretKey,
bucket = bucket,
region = region,
security = "public",
pathPrefix = bucketPrefix ,
bDebug=true
) />
```
=> FC-3160 - add bDebug (default false) to location config

packages/cdn/s3.cfc
changed
`<cfset var s3path = "s3://#arguments.config.accessKeyId#:#arguments.config.awsSecretKey#@#arguments.config.bucket##lcase(arguments.config.pathPrefix)##lcase(arguments.dir)#" /> `
To	
`<cfset var s3path = getS3Path(config=arguments.config,file=arguments.dir) />`
=> FC-3161 - ioGetDirectoryListing() use getS3Path()

packages/cdn/s3.cfc
ioCopyFile() and ioMoveFile() have optional config arguments 
so have added checks to set bDebug flag
=> FC-3160 - bDebug fix for functions with option config arguments

packages/cdn/s3.cfc
error thrown if ti threads try and delete cache at the same time 
Message : the value from key [/images/image.jpg] is NULL, which is the same as not existing in CFML 
Also, oldest file may not actually be deleted; deletes the last old file it loops through
=> FC-3171 - S3 addCachedFile() not thread safe

packages/events/bulkupload.cfc
If an image file name has any special characters it fails to be found because ioGetFileLocation will default to normalizePath removing any special characters for it’s lookup.
=> Bulk Image Upload & special characters

packages/dbgateways/MySQLGateway.cfc
ColdFusion 2018 throws an error when the # are used in this expression.  Removing them solves the issue.
=> Remove unnecessary #

packages/farcry/i18nUtil.cfc, packages/types/dmProfile.cfc
Add query method to i18nutil to return locales as a query. Update dmProfile to use new method.
This fixes list related issues as described on the forum: https://discourse.farcrycore.org/t/profile-locales/1741
This has only been tested with Lucee 5.3.12.1. Planning to test with ColdFusion 2021 Standard. Open to suggestions for other tests.
=> i18nutil patch
